//! MPSGraph device + builder context.
//!
//! Wraps the autogenerated `objc2-metal-performance-shaders-graph` types into
//! a small Rust-idiomatic surface that the rest of the workspace can use
//! without writing `unsafe` blocks or learning the Apple ObjC selectors.

use objc2::rc::Retained;
use objc2::runtime::ProtocolObject;
use objc2_metal::{MTLCreateSystemDefaultDevice, MTLDevice};
use objc2_metal_performance_shaders_graph::{MPSGraph, MPSGraphDevice};

/// Process-wide MPSGraph context.
///
/// `MPSGraphDevice` is cheap to clone (objc retain), so we keep a single
/// instance and hand out new graph builders on demand.
pub struct MpsGraphContext {
    device: Retained<MPSGraphDevice>,
    mtl_device: Retained<ProtocolObject<dyn MTLDevice>>,
}

impl MpsGraphContext {
    /// Initialise from the system default Metal device.
    ///
    /// This is the same singleton Apple device used by Candle / our existing
    /// `MetalContext`, so buffers can be shared at the ObjC level (with a
    /// transmute helper) — see the Phase 3 wiring plan.
    pub fn new() -> Result<Self, MpsGraphError> {
        let mtl_device = MTLCreateSystemDefaultDevice().ok_or(MpsGraphError::NoDevice)?;
        let device = unsafe { MPSGraphDevice::deviceWithMTLDevice(mtl_device.as_ref()) };
        Ok(Self { device, mtl_device })
    }

    /// Borrow the underlying `MPSGraphDevice` for graph compilation.
    pub fn device(&self) -> &MPSGraphDevice {
        &self.device
    }

    /// Borrow the underlying `MTLDevice` (for command queue / buffer alloc).
    pub fn mtl_device(&self) -> &ProtocolObject<dyn MTLDevice> {
        &self.mtl_device
    }

    /// Create a fresh empty `MPSGraph`. Caller adds nodes then compiles.
    pub fn new_graph(&self) -> Retained<MPSGraph> {
        unsafe { MPSGraph::new() }
    }
}

#[derive(Debug, thiserror::Error)]
pub enum MpsGraphError {
    #[error("MTLCreateSystemDefaultDevice returned nil — no Metal device on this machine")]
    NoDevice,
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::mpsgraph::{
        MatmulGraph2D, RmsNormGraph, compile, run_sync, shape_from_dims, tensor_data_from_buffer,
    };
    use objc2_metal::{MTLBuffer, MTLDevice, MTLResourceOptions};
    use objc2_metal_performance_shaders::MPSDataType;
    use std::ptr::NonNull;

    /// Smoke test: the FFI links and a graph can be allocated.
    #[test]
    fn ctx_init_and_new_graph_is_distinct() {
        let ctx = MpsGraphContext::new().expect("Metal device");
        let g1 = ctx.new_graph();
        let g2 = ctx.new_graph();
        // Distinct ObjC objects (different addresses)
        assert!(!std::ptr::eq(&*g1 as *const _, &*g2 as *const _));
    }

    /// PoC 1 — matmul 2×2 with input feeds and result read-back.
    ///
    /// Verifies the full pipeline: graph build → compile → MTLBuffer feed →
    /// `runWithMTLCommandQueue` → readback. Numerical reference:
    ///   A = [[1, 2], [3, 4]], B = [[5, 6], [7, 8]]
    ///   C = A · B = [[19, 22], [43, 50]]
    #[test]
    fn matmul_2x2_numerical_correctness() {
        let ctx = MpsGraphContext::new().expect("Metal device");
        let mtl_device = ctx.mtl_device();

        // Build a fresh graph for this test.
        let mm = MatmulGraph2D::build(ctx.new_graph(), 2, 2, 2);
        let exe = compile(&mm.graph, ctx.device(), &mm.feeds, &[&*mm.c]);

        // Allocate Metal buffers (shared storage so we can read back from CPU).
        let a_data: [f32; 4] = [1.0, 2.0, 3.0, 4.0];
        let b_data: [f32; 4] = [5.0, 6.0, 7.0, 8.0];
        let bytes = std::mem::size_of::<[f32; 4]>();

        let a_buf = unsafe {
            mtl_device
                .newBufferWithBytes_length_options(
                    NonNull::new(a_data.as_ptr() as *mut std::ffi::c_void).unwrap(),
                    bytes,
                    MTLResourceOptions::StorageModeShared,
                )
                .expect("alloc A")
        };
        let b_buf = unsafe {
            mtl_device
                .newBufferWithBytes_length_options(
                    NonNull::new(b_data.as_ptr() as *mut std::ffi::c_void).unwrap(),
                    bytes,
                    MTLResourceOptions::StorageModeShared,
                )
                .expect("alloc B")
        };
        let c_buf = mtl_device
            .newBufferWithLength_options(bytes, MTLResourceOptions::StorageModeShared)
            .expect("alloc C");

        let shape = shape_from_dims(&[2, 2]);
        let a_td = tensor_data_from_buffer(&a_buf, &shape, MPSDataType::Float32);
        let b_td = tensor_data_from_buffer(&b_buf, &shape, MPSDataType::Float32);
        let c_td = tensor_data_from_buffer(&c_buf, &shape, MPSDataType::Float32);

        let queue = mtl_device.newCommandQueue().expect("queue");
        let _ = run_sync(&exe, &queue, &[&*a_td, &*b_td], &[&*c_td]);

        // Read C back from shared MTLBuffer.
        let result: [f32; 4] = unsafe {
            let ptr = c_buf.contents().as_ptr() as *const f32;
            [*ptr, *ptr.add(1), *ptr.add(2), *ptr.add(3)]
        };
        assert_eq!(result, [19.0, 22.0, 43.0, 50.0], "matmul 2×2 mismatch");
    }

    /// PoC 1b — RmsNorm decomposition probe.
    ///
    /// Verifies the 6-node manual decomposition matches a CPU reference
    /// within float tolerance. `m=2, hidden=4` with eps=1e-6.
    #[test]
    fn rms_norm_matches_cpu_reference() {
        let ctx = MpsGraphContext::new().expect("Metal device");
        let mtl_device = ctx.mtl_device();

        let m = 2usize;
        let hidden = 4usize;
        let eps = 1e-6_f32;

        let rn = RmsNormGraph::build(ctx.new_graph(), m, hidden, eps);
        let exe = compile(&rn.graph, ctx.device(), &rn.feeds, &[&*rn.y]);

        // Inputs.
        let x: [f32; 8] = [1.0, 2.0, 3.0, 4.0, -1.0, -2.0, -3.0, -4.0];
        let weight: [f32; 4] = [0.5, 1.0, 1.5, 2.0];

        // CPU reference.
        let mut expected = [0.0_f32; 8];
        for row in 0..m {
            let off = row * hidden;
            let mean_sq: f32 =
                x[off..off + hidden].iter().map(|v| v * v).sum::<f32>() / hidden as f32;
            let inv = (mean_sq + eps).sqrt().recip();
            for c in 0..hidden {
                expected[off + c] = x[off + c] * inv * weight[c];
            }
        }

        let x_buf = unsafe {
            mtl_device
                .newBufferWithBytes_length_options(
                    NonNull::new(x.as_ptr() as *mut std::ffi::c_void).unwrap(),
                    std::mem::size_of_val(&x),
                    MTLResourceOptions::StorageModeShared,
                )
                .expect("alloc x")
        };
        let w_buf = unsafe {
            mtl_device
                .newBufferWithBytes_length_options(
                    NonNull::new(weight.as_ptr() as *mut std::ffi::c_void).unwrap(),
                    std::mem::size_of_val(&weight),
                    MTLResourceOptions::StorageModeShared,
                )
                .expect("alloc w")
        };
        let y_buf = mtl_device
            .newBufferWithLength_options(
                std::mem::size_of_val(&expected),
                MTLResourceOptions::StorageModeShared,
            )
            .expect("alloc y");

        let x_shape = shape_from_dims(&[m, hidden]);
        let w_shape = shape_from_dims(&[hidden]);
        let x_td = tensor_data_from_buffer(&x_buf, &x_shape, MPSDataType::Float32);
        let w_td = tensor_data_from_buffer(&w_buf, &w_shape, MPSDataType::Float32);
        let y_td = tensor_data_from_buffer(&y_buf, &x_shape, MPSDataType::Float32);

        let queue = mtl_device.newCommandQueue().expect("queue");
        let _ = run_sync(&exe, &queue, &[&*x_td, &*w_td], &[&*y_td]);

        let got: Vec<f32> = unsafe {
            let ptr = y_buf.contents().as_ptr() as *const f32;
            (0..m * hidden).map(|i| *ptr.add(i)).collect()
        };

        let mut max_abs = 0.0_f32;
        for (i, (&a, &b)) in got.iter().zip(expected.iter()).enumerate() {
            let d = (a - b).abs();
            if d > max_abs {
                max_abs = d;
            }
            assert!(d < 1e-5, "RmsNorm mismatch at {i}: got {a}, expected {b}");
        }
        // Sanity: the test isn't trivially zeros-vs-zeros.
        assert!(got.iter().any(|&v| v.abs() > 1e-3));
        eprintln!("RmsNorm max_abs error: {max_abs:.2e}");
    }
}
