//! Numerical parity test for `SparseMoeBlock::forward` against the MLX reference fixture.
//!
//! What we're proving: our Rust port of `mlx_lm.models.qwen3_next.Qwen3NextSparseMoeBlock`
//! produces the same block output that MLX produced for layer 0 of the
//! `mlx-community/Qwen3.6-35B-A3B-mxfp4` checkpoint when fed the same
//! post-`post_attention_layernorm` input.
//!
//! ## Fixture files (all under `tests/fixtures/`)
//!
//! - `layer0_moe.safetensors` — the **golden** input/output pair, generated by
//!   `scripts/generate_qwen3_5_moe_fixtures.py`. Keys: `x_post_ln` (the
//!   post-`post_attention_layernorm` activation, fed to `mlp`), `y` (MLX reference output).
//!   Checked into git (~100 KB, seq_len=4, hidden=2048).
//! - `layer0_moe_weights.safetensors` — **dequantized fp32** projections + norms for layer 0
//!   MoE. Generated by `scripts/dump_qwen3_5_moe_layer_weights.py` (~3 GB — 256 experts × 3
//!   projections × 512×2048 fp32 + shared). **Not** checked in; the test skips when absent.
//!
//! ## Skipping behavior
//!
//! If the weights fixture is missing, the test prints a hint and returns `Ok`. CI that lacks
//! the 19 GB HF checkpoint can still exercise the lib-level shape/invariant tests without
//! this one failing.
//!
//! ## Tolerance — two independent bounds
//!
//! The MLX reference runs the full MoE block in bf16; we run in f32. `moe_trace.rs` localized
//! the gap stage-by-stage and found a mode of divergence unique to MoE:
//!
//!   **Top-k tie-break at bf16 resolution.** When two experts' softmax probabilities fall
//!   within bf16's ~4e-5 absolute resolution at the 8th vs 9th cutoff, MLX (bf16) and our
//!   f32 path legitimately pick different members. Concretely, on the layer-0 fixture
//!   token 1 picks expert 50 in f32 but 175 in bf16 — both probabilities quantize to the
//!   same bf16 value `1.03149e-2`, so the *actual* difference is tie-breaker noise, not a
//!   routing bug. On those tokens the routed branch diverges by the full weight of one
//!   swapped expert (~12.5% score × |out_50 − out_175|), inflating `rel_L2` on the routed
//!   sub-output to ~19% while leaving per-element `max_abs` well-contained.
//!
//! We therefore gate on **two bounds**:
//!
//!   1. `max_abs < 1e-2` — the per-element precision gate. A structural routing bug (wrong
//!      projection layout, incorrect gate wiring, misplaced sigmoid) produces per-element
//!      errors much larger than the 5.5e-3 bf16↔f32 gap measured in `self_attn_fixture`.
//!   2. `rel_L2 < 1e-1` — the global shape gate. Even with one top-k swap per 4 tokens the
//!      full-block rel_L2 stays under ~6%; bounds much larger than this indicate something
//!      more systemic (e.g. missing the shared_expert path entirely).
//!
//! Both must pass. The asymmetry — max_abs tight, rel_L2 loose — is deliberate: it passes
//! honest bf16 tie-break divergence while still catching a real algorithmic regression.

use std::collections::HashMap;
use std::path::{Path, PathBuf};

use candle_core::{safetensors as cst, DType, Device, Tensor};
use candle_nn::Linear;
use lumen_model::qwen3_5_moe::moe::{
    MoeDims, SharedExpert, SparseMoeBlock, SparseMoeRuntime, SwitchMlp,
};

fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures")
}

fn take_f32(map: &HashMap<String, Tensor>, name: &str) -> Tensor {
    let t = map
        .get(name)
        .unwrap_or_else(|| panic!("missing tensor `{name}` in fixture"));
    assert_eq!(
        t.dtype(),
        DType::F32,
        "expected `{name}` to be f32 but got {:?}",
        t.dtype()
    );
    t.clone()
}

fn skip_if_missing(path: &Path) -> bool {
    if !path.exists() {
        eprintln!(
            "skipping: {} not found. Regenerate with\n    \
             python scripts/dump_qwen3_5_moe_layer_weights.py --layer 0 --block moe",
            path.display()
        );
        return true;
    }
    false
}

/// Layer-0 MoE constants copied from `tests/fixtures/qwen3_5_moe_config.json`. Hardcoded
/// here (instead of re-parsing the json) to keep the test self-contained — drift in the
/// real config should surface as a loud compile/runtime failure, not a silent fixture skew.
fn layer0_dims() -> MoeDims {
    MoeDims {
        hidden_size: 2048,
        num_experts: 256,
        moe_intermediate_size: 512,
        shared_expert_intermediate_size: 512,
    }
}

fn layer0_runtime() -> SparseMoeRuntime {
    SparseMoeRuntime {
        dims: layer0_dims(),
        top_k: 8,
        norm_topk_prob: true,
    }
}

fn relative_l2(a: &Tensor, b: &Tensor) -> f32 {
    let diff = (a - b).unwrap();
    let num = diff
        .sqr()
        .unwrap()
        .sum_all()
        .unwrap()
        .to_scalar::<f32>()
        .unwrap()
        .sqrt();
    let den = b
        .sqr()
        .unwrap()
        .sum_all()
        .unwrap()
        .to_scalar::<f32>()
        .unwrap()
        .sqrt()
        .max(1e-12);
    num / den
}

#[test]
fn sparse_moe_forward_matches_mlx_fixture_layer0() {
    let dir = fixtures_dir();
    let weights_path = dir.join("layer0_moe_weights.safetensors");
    if skip_if_missing(&weights_path) {
        return;
    }
    let input_path = dir.join("layer0_moe.safetensors");

    // CPU: ~5.5e-3 bf16↔f32 gap is a small-enough needle to thread without also reasoning
    // about Metal kernel rounding. Fixtures are ~3 GB so this test is slow — ~30-60s on
    // the M-series laptops used for development.
    let device = Device::Cpu;

    let weights = cst::load(&weights_path, &device).unwrap();
    let fixture = cst::load(&input_path, &device).unwrap();

    let dims = layer0_dims();
    let rt = layer0_runtime();

    let x_post_ln = take_f32(&fixture, "x_post_ln");
    let y_ref = take_f32(&fixture, "y");
    let x = x_post_ln.unsqueeze(0).unwrap();
    let y_ref = y_ref.unsqueeze(0).unwrap();

    // Assemble the sub-linears from dequantized weights.
    let gate = Linear::new(take_f32(&weights, "gate.weight"), None);
    let shared_expert_gate =
        Linear::new(take_f32(&weights, "shared_expert_gate.weight"), None);
    let se_gate = Linear::new(take_f32(&weights, "shared_expert.gate_proj.weight"), None);
    let se_up = Linear::new(take_f32(&weights, "shared_expert.up_proj.weight"), None);
    let se_down = Linear::new(take_f32(&weights, "shared_expert.down_proj.weight"), None);

    let switch = SwitchMlp::new(
        take_f32(&weights, "switch_mlp.gate_proj.weight"),
        take_f32(&weights, "switch_mlp.up_proj.weight"),
        take_f32(&weights, "switch_mlp.down_proj.weight"),
        dims,
    )
    .expect("switch_mlp shapes match config");

    // Sanity-check shapes match the ones derived from config.
    let shapes = dims.shapes();
    assert_eq!(gate.weight().dims(), shapes.gate.as_slice());
    assert_eq!(
        shared_expert_gate.weight().dims(),
        shapes.shared_expert_gate.as_slice()
    );
    assert_eq!(se_gate.weight().dims(), shapes.shared_expert_gate_proj.as_slice());
    assert_eq!(se_up.weight().dims(), shapes.shared_expert_up_proj.as_slice());
    assert_eq!(
        se_down.weight().dims(),
        shapes.shared_expert_down_proj.as_slice()
    );

    let se_gate_up = Linear::new(
        Tensor::cat(&[se_gate.weight(), se_up.weight()], 0).unwrap(),
        None,
    );
    let shared_expert = SharedExpert::new(
        se_gate_up.into(),
        se_down.into(),
        dims.shared_expert_intermediate_size,
    );
    let block = SparseMoeBlock::new(
        rt,
        gate.into(),
        shared_expert_gate.into(),
        shared_expert,
        switch.into(),
    );

    let y = block.forward(&x).unwrap();
    assert_eq!(y.dims(), y_ref.dims());

    let err = relative_l2(&y, &y_ref);
    let max_diff = (&y - &y_ref)
        .unwrap()
        .abs()
        .unwrap()
        .max_all()
        .unwrap()
        .to_scalar::<f32>()
        .unwrap();
    let y_sum = y.sum_all().unwrap().to_scalar::<f32>().unwrap();
    let y_ref_sum = y_ref.sum_all().unwrap().to_scalar::<f32>().unwrap();
    println!(
        "sparse_moe layer0 parity: rel_L2 = {err:.4e}, max_abs = {max_diff:.4e}, \
         y_sum = {y_sum:.4} (ref {y_ref_sum:.4})"
    );

    assert!(
        max_diff < 1e-2,
        "max_abs {max_diff:.4e} exceeds 1e-2 per-element precision gate; the bf16↔f32 \
         floor on this block is ~6e-3 (measured), so a larger element-wise error means a \
         structural bug rather than rounding. Run `cargo test --test moe_trace` to localize."
    );
    assert!(
        err < 1e-1,
        "relative L2 {err:.4e} exceeds 1e-1 global shape gate; even a full top-k tie-break \
         swap at bf16 resolution stays under ~6% here, so exceeding this indicates something \
         systemic (missing shared_expert path, wrong projection transpose, etc.)."
    );
}
