//! Numerical parity test for `SelfAttention::forward` against the MLX reference fixture.
//!
//! What we're proving: our Rust port of `mlx_lm.models.qwen3_next.Qwen3NextAttention` produces
//! the same block output that MLX produced for layer 3 when fed the same post-LayerNorm input.
//!
//! ## Fixture files (all under `tests/fixtures/`)
//!
//! - `layer3_self_attn.safetensors` — the **golden** input/output pair, generated by
//!   `scripts/generate_qwen3_5_moe_fixtures.py`. Keys: `x_post_ln` (post-`input_layernorm`
//!   activation, fed to `self_attn`), `y` (MLX reference output). Checked into git (~100 KB).
//! - `layer3_self_attn_weights.safetensors` — **dequantized fp32** projections + norms for
//!   layer 3. Generated by `scripts/dump_qwen3_5_moe_layer_weights.py` (~104 MB). **Not**
//!   checked in; the test skips when absent.
//!
//! ## Skipping behavior
//!
//! If the weights fixture is missing, the test prints a hint and returns `Ok`. CI that lacks
//! the 19 GB HF checkpoint can still exercise the lib-level shape/invariant tests without
//! this one failing.
//!
//! ## Tolerance
//!
//! The MLX reference runs entirely in bf16 (inputs, activations, and intermediates) while we
//! run in f32. To size the bound empirically we ran MLX's own attention twice — once with bf16
//! input and once with f32 input — on the same weights. That internal bf16↔f32 mismatch was
//! `5.51e-3` relative L2 / `7.6e-3` max-abs (recorded 2026-04-23 from mlx-lm 0.31.3). Our Rust
//! f32 reproduction reaches that same `5.5e-3` floor down to `<1e-6` algorithmic error.
//!
//! We therefore set the bound at `1e-2`: a factor of ~2× slack above the irreducible dtype
//! gap, so any legitimate algorithmic bug (missing rotation, wrong head ordering, mask errors,
//! etc.) blows through it while honest f32 rounding passes. Tighter bounds require either
//! running the Rust path in bf16 or regenerating the fixture from an f32 MLX run.

use std::collections::HashMap;
use std::path::{Path, PathBuf};

use candle_core::{safetensors as cst, DType, Device, Tensor};
use candle_nn::{Linear, RmsNorm};
use lumen_model::qwen3_5_moe::self_attn::{SelfAttention, SelfAttnDims, SelfAttnRuntime};

fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures")
}

/// Load a named f32 tensor from a safetensors file and ensure the dtype matches.
fn take_f32(map: &HashMap<String, Tensor>, name: &str) -> Tensor {
    let t = map
        .get(name)
        .unwrap_or_else(|| panic!("missing tensor `{name}` in fixture"));
    assert_eq!(
        t.dtype(),
        DType::F32,
        "expected `{name}` to be f32 but got {:?}",
        t.dtype()
    );
    t.clone()
}

fn skip_if_missing(path: &Path) -> bool {
    if !path.exists() {
        eprintln!(
            "skipping: {} not found. Regenerate with\n    \
             python scripts/dump_qwen3_5_moe_layer_weights.py --layer 3 --block self_attn",
            path.display()
        );
        return true;
    }
    false
}

/// Layer-3 `self_attn.*` constants copied from `crates/lumen-model/tests/fixtures/qwen3_5_moe_config.json`.
/// Hardcoded here (instead of re-parsing the json) to keep the test self-contained — if the
/// real config drifts we want a loud compile-level signal, not a silent drift in the fixture.
fn layer3_dims() -> SelfAttnDims {
    SelfAttnDims {
        hidden_size: 2048,
        num_heads: 16,
        num_kv_heads: 2,
        head_dim: 256,
        attn_output_gate: true,
        rotary_dim: 64,
    }
}

fn layer3_runtime() -> SelfAttnRuntime {
    SelfAttnRuntime {
        dims: layer3_dims(),
        rope_theta: 10_000_000.0,
        rms_norm_eps: 1e-6,
    }
}

/// Relative L2 error: ‖a − b‖₂ / ‖b‖₂. Bound discussed in the module-level doc (1e-2, derived
/// from the empirically-measured MLX bf16↔f32 gap of 5.5e-3).
fn relative_l2(a: &Tensor, b: &Tensor) -> f32 {
    let diff = (a - b).unwrap();
    let num = diff
        .sqr()
        .unwrap()
        .sum_all()
        .unwrap()
        .to_scalar::<f32>()
        .unwrap()
        .sqrt();
    let den = b
        .sqr()
        .unwrap()
        .sum_all()
        .unwrap()
        .to_scalar::<f32>()
        .unwrap()
        .sqrt()
        .max(1e-12);
    num / den
}

#[test]
fn self_attn_forward_matches_mlx_fixture_layer3() {
    let dir = fixtures_dir();
    let weights_path = dir.join("layer3_self_attn_weights.safetensors");
    if skip_if_missing(&weights_path) {
        return;
    }
    let input_path = dir.join("layer3_self_attn.safetensors");

    // CPU-only: bf16 ↔ f32 parity is already a small-enough needle to thread without having
    // to also reason about Metal kernel rounding.
    let device = Device::Cpu;

    let weights = cst::load(&weights_path, &device).unwrap();
    let fixture = cst::load(&input_path, &device).unwrap();

    let dims = layer3_dims();
    let rt = layer3_runtime();

    // The fixture's `x_post_ln` is what MLX's layer produces *after* input_layernorm and
    // hands into `self_attn(...)`. So we don't need to re-apply the layernorm here.
    let x_post_ln = take_f32(&fixture, "x_post_ln");
    let y_ref = take_f32(&fixture, "y");
    // Re-shape to the [B=1, L, hidden] layout our forward expects. The Python dump stored
    // the first (and only) batch row as [L, hidden] via `x[0]`.
    let x = x_post_ln.unsqueeze(0).unwrap();
    let y_ref = y_ref.unsqueeze(0).unwrap();

    // Assemble Linear/RmsNorm from the dequantized weights.
    let q_proj = Linear::new(take_f32(&weights, "q_proj.weight"), None);
    let k_proj = Linear::new(take_f32(&weights, "k_proj.weight"), None);
    let v_proj = Linear::new(take_f32(&weights, "v_proj.weight"), None);
    let o_proj = Linear::new(take_f32(&weights, "o_proj.weight"), None);
    let q_norm = RmsNorm::new(take_f32(&weights, "q_norm.weight"), rt.rms_norm_eps);
    let k_norm = RmsNorm::new(take_f32(&weights, "k_norm.weight"), rt.rms_norm_eps);

    // Sanity-check shapes match the ones derived from config.
    let shapes = dims.shapes();
    for (name, tensor, expected) in [
        ("q_proj", q_proj.weight(), &shapes.q_proj),
        ("k_proj", k_proj.weight(), &shapes.k_proj),
        ("v_proj", v_proj.weight(), &shapes.v_proj),
        ("o_proj", o_proj.weight(), &shapes.o_proj),
        ("q_norm", q_norm.weight(), &shapes.q_norm),
        ("k_norm", k_norm.weight(), &shapes.k_norm),
    ] {
        assert_eq!(
            tensor.dims(),
            expected.as_slice(),
            "{name} has unexpected shape"
        );
    }

    let qkv_proj = Linear::new(
        Tensor::cat(&[q_proj.weight(), k_proj.weight(), v_proj.weight()], 0).unwrap(),
        None,
    );

    let mut attn = SelfAttention::new(
        rt,
        qkv_proj.into(),
        o_proj.into(),
        q_norm,
        k_norm,
    );

    // MLX's `layer.self_attn(x)` defaults to `mask=None` (bidirectional). The golden fixture
    // was dumped with that default, so the parity check here also uses `None`. Production
    // prefill would pass `SelfAttention::prefill_causal_mask(L, dtype, device)`.
    let y = attn.forward(&x, 0, None).unwrap();
    assert_eq!(y.dims(), y_ref.dims());

    let err = relative_l2(&y, &y_ref);
    let max_diff = (&y - &y_ref)
        .unwrap()
        .abs()
        .unwrap()
        .max_all()
        .unwrap()
        .to_scalar::<f32>()
        .unwrap();
    let y_sum = y.sum_all().unwrap().to_scalar::<f32>().unwrap();
    let y_ref_sum = y_ref.sum_all().unwrap().to_scalar::<f32>().unwrap();
    println!(
        "self_attn layer3 parity: rel_L2 = {err:.4e}, max_abs = {max_diff:.4e}, \
         y_sum = {y_sum:.4} (ref {y_ref_sum:.4})"
    );

    assert!(
        err < 1e-2,
        "relative L2 error {err:.4e} exceeds 1e-2 bound; \
         pure bf16↔f32 precision gap from MLX is ~5.5e-3, so a larger error indicates a \
         structural bug, not rounding. Run `cargo test --test self_attn_trace` to localize."
    );
}
