//! Step-by-step numerical comparison against MLX-dumped intermediates for layer 3.
//!
//! Diagnostic-only: prints relative-L2 error at each stage so structural bugs jump out. Ships
//! a single test; skips when the trace fixture (generated by a one-shot python probe that
//! lives alongside `dump_qwen3_5_moe_layer_weights.py`) isn't present.

use std::collections::HashMap;
use std::path::{Path, PathBuf};

use candle_core::{safetensors as cst, Device, Tensor, D};
use candle_nn::{ops, rotary_emb, Linear, Module, RmsNorm};

fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures")
}

fn take(map: &HashMap<String, Tensor>, name: &str) -> Tensor {
    map.get(name)
        .unwrap_or_else(|| panic!("missing `{name}` in trace fixture"))
        .clone()
}

fn rel_l2(a: &Tensor, b: &Tensor) -> f32 {
    let n = (a - b)
        .unwrap()
        .sqr()
        .unwrap()
        .sum_all()
        .unwrap()
        .to_scalar::<f32>()
        .unwrap()
        .sqrt();
    let d = b
        .sqr()
        .unwrap()
        .sum_all()
        .unwrap()
        .to_scalar::<f32>()
        .unwrap()
        .sqrt()
        .max(1e-12);
    n / d
}

fn skip_if_missing(path: &Path) -> bool {
    if !path.exists() {
        eprintln!("skipping trace: {} not present", path.display());
        return true;
    }
    false
}

fn build_rope_table(
    rotary_dim: usize,
    seq_len: usize,
    offset: usize,
    theta: f32,
    device: &Device,
) -> (Tensor, Tensor) {
    let half = rotary_dim / 2;
    let inv_freqs: Vec<f32> = (0..half)
        .map(|i| 1.0 / theta.powf((2 * i) as f32 / rotary_dim as f32))
        .collect();
    let inv_freqs = Tensor::from_vec(inv_freqs, (half,), device).unwrap();
    let positions: Vec<f32> = (0..seq_len).map(|t| (offset + t) as f32).collect();
    let positions = Tensor::from_vec(positions, (seq_len,), device).unwrap();
    let angles = positions
        .unsqueeze(1)
        .unwrap()
        .broadcast_mul(&inv_freqs.unsqueeze(0).unwrap())
        .unwrap();
    (angles.cos().unwrap(), angles.sin().unwrap())
}

fn apply_partial_rope(x: &Tensor, cos: &Tensor, sin: &Tensor, rotary_dim: usize) -> Tensor {
    let head_dim = x.dim(D::Minus1).unwrap();
    let rot = x
        .narrow(D::Minus1, 0, rotary_dim)
        .unwrap()
        .contiguous()
        .unwrap();
    let pass = x.narrow(D::Minus1, rotary_dim, head_dim - rotary_dim).unwrap();
    let rot = rotary_emb::rope(&rot, cos, sin).unwrap();
    Tensor::cat(&[&rot, &pass], D::Minus1).unwrap()
}

fn repeat_kv(x: &Tensor, n: usize) -> Tensor {
    if n == 1 {
        return x.clone();
    }
    let (b, kv, l, d) = x.dims4().unwrap();
    x.unsqueeze(2)
        .unwrap()
        .expand((b, kv, n, l, d))
        .unwrap()
        .reshape((b, kv * n, l, d))
        .unwrap()
}

fn causal_mask(l: usize, device: &Device) -> Tensor {
    let mut data = vec![0f32; l * l];
    for i in 0..l {
        for j in (i + 1)..l {
            data[i * l + j] = f32::NEG_INFINITY;
        }
    }
    Tensor::from_vec(data, (l, l), device).unwrap()
}

#[test]
fn trace_layer3_step_by_step() {
    let dir = fixtures_dir();
    let weights_path = dir.join("layer3_self_attn_weights.safetensors");
    let trace_path = dir.join("layer3_self_attn_trace.safetensors");
    let fixture_path = dir.join("layer3_self_attn.safetensors");
    if skip_if_missing(&weights_path) || skip_if_missing(&trace_path) {
        return;
    }

    let device = Device::Cpu;
    let weights = cst::load(&weights_path, &device).unwrap();
    let trace = cst::load(&trace_path, &device).unwrap();
    let fixture = cst::load(&fixture_path, &device).unwrap();

    let x_post_ln = take(&fixture, "x_post_ln"); // [L, hidden]
    let x = x_post_ln.unsqueeze(0).unwrap(); // [1, L, hidden]
    let (_, seq_len, _hidden) = x.dims3().unwrap();
    let h = 16;
    let kv = 2;
    let hd = 256;
    let rotary_dim = 64;
    let rope_theta = 10_000_000f32;
    let eps = 1e-6;

    let q_proj = Linear::new(take(&weights, "q_proj.weight"), None);
    let k_proj = Linear::new(take(&weights, "k_proj.weight"), None);
    let v_proj = Linear::new(take(&weights, "v_proj.weight"), None);
    let o_proj = Linear::new(take(&weights, "o_proj.weight"), None);
    let q_norm = RmsNorm::new(take(&weights, "q_norm.weight"), eps);
    let k_norm = RmsNorm::new(take(&weights, "k_norm.weight"), eps);

    // Step 1: q_raw
    let q_raw_rust = q_proj.forward(&x).unwrap().squeeze(0).unwrap();
    let q_raw_ref = take(&trace, "q_raw");
    println!("[1] q_raw      rel_L2 = {:.3e}", rel_l2(&q_raw_rust, &q_raw_ref));

    // Step 2: split into queries + gate (before norm)
    let q_full = q_raw_rust.reshape((seq_len, h, 2 * hd)).unwrap();
    let q_before_norm_rust = q_full.narrow(D::Minus1, 0, hd).unwrap().contiguous().unwrap();
    let gate_pre_rust = q_full.narrow(D::Minus1, hd, hd).unwrap().contiguous().unwrap();
    let q_before_ref = take(&trace, "q_before_norm");
    let gate_pre_ref = take(&trace, "gate_pre");
    println!(
        "[2a] q_before_norm rel_L2 = {:.3e}",
        rel_l2(&q_before_norm_rust, &q_before_ref)
    );
    println!(
        "[2b] gate_pre      rel_L2 = {:.3e}",
        rel_l2(&gate_pre_rust, &gate_pre_ref)
    );

    let k_raw = k_proj.forward(&x).unwrap().squeeze(0).unwrap();
    let k_before_norm_rust = k_raw.reshape((seq_len, kv, hd)).unwrap();
    let k_before_ref = take(&trace, "k_before_norm");
    println!(
        "[3] k_before_norm rel_L2 = {:.3e}",
        rel_l2(&k_before_norm_rust, &k_before_ref)
    );

    // Step 3: apply QK-norm
    let q_after_norm_rust = q_norm
        .forward(&q_before_norm_rust)
        .unwrap()
        .transpose(0, 1)
        .unwrap()
        .contiguous()
        .unwrap(); // [H, L, HD]
    let k_after_norm_rust = k_norm
        .forward(&k_before_norm_rust)
        .unwrap()
        .transpose(0, 1)
        .unwrap()
        .contiguous()
        .unwrap(); // [KV, L, HD]
    let q_after_norm_ref = take(&trace, "q_after_norm");
    let k_after_norm_ref = take(&trace, "k_after_norm");
    println!(
        "[4a] q_after_norm rel_L2 = {:.3e}",
        rel_l2(&q_after_norm_rust, &q_after_norm_ref)
    );
    println!(
        "[4b] k_after_norm rel_L2 = {:.3e}",
        rel_l2(&k_after_norm_rust, &k_after_norm_ref)
    );

    // Step 4: RoPE
    let (cos, sin) = build_rope_table(rotary_dim, seq_len, 0, rope_theta, &device);
    // q_after_norm has shape [H, L, HD] — add batch dim for rope helper semantics
    let q_after_rope_rust = apply_partial_rope(
        &q_after_norm_rust.unsqueeze(0).unwrap(),
        &cos,
        &sin,
        rotary_dim,
    )
    .squeeze(0)
    .unwrap();
    let k_after_rope_rust = apply_partial_rope(
        &k_after_norm_rust.unsqueeze(0).unwrap(),
        &cos,
        &sin,
        rotary_dim,
    )
    .squeeze(0)
    .unwrap();
    let q_after_rope_ref = take(&trace, "q_after_rope");
    let k_after_rope_ref = take(&trace, "k_after_rope");
    println!(
        "[5a] q_after_rope rel_L2 = {:.3e}",
        rel_l2(&q_after_rope_rust, &q_after_rope_ref)
    );
    println!(
        "[5b] k_after_rope rel_L2 = {:.3e}",
        rel_l2(&k_after_rope_rust, &k_after_rope_ref)
    );

    // Step 5: SDPA
    let v_raw = v_proj.forward(&x).unwrap().squeeze(0).unwrap();
    let v_t = v_raw.reshape((seq_len, kv, hd)).unwrap().transpose(0, 1).unwrap().contiguous().unwrap(); // [KV, L, HD]
    let v_ref = take(&trace, "v_transposed");
    println!(
        "[6] v_transposed rel_L2 = {:.3e}",
        rel_l2(&v_t, &v_ref)
    );

    let q4 = q_after_rope_rust.unsqueeze(0).unwrap(); // [1, H, L, HD]
    let k4 = k_after_rope_rust.unsqueeze(0).unwrap();
    let v4 = v_t.unsqueeze(0).unwrap();
    let group = h / kv;
    let k4 = repeat_kv(&k4, group);
    let v4 = repeat_kv(&v4, group);

    let scale = (hd as f64).powf(-0.5);
    let scores =
        (q4.matmul(&k4.transpose(D::Minus2, D::Minus1).unwrap()).unwrap() * scale).unwrap();
    let mask = causal_mask(seq_len, &device);
    let scores = scores.broadcast_add(&mask).unwrap();
    let attn = ops::softmax_last_dim(&scores).unwrap();
    let sdpa = attn.matmul(&v4).unwrap().squeeze(0).unwrap(); // [H, L, HD]
    let sdpa_ref = take(&trace, "sdpa_out");
    println!("[7] sdpa_out     rel_L2 = {:.3e}", rel_l2(&sdpa, &sdpa_ref));

    // Step 6: flatten + gate + o_proj
    let sdpa_flat = sdpa
        .transpose(0, 1)
        .unwrap()
        .contiguous()
        .unwrap()
        .reshape((seq_len, h * hd))
        .unwrap();
    let sdpa_flat_ref = take(&trace, "sdpa_flat");
    println!(
        "[8] sdpa_flat    rel_L2 = {:.3e}",
        rel_l2(&sdpa_flat, &sdpa_flat_ref)
    );

    let gate_flat = gate_pre_rust.reshape((seq_len, h * hd)).unwrap();
    let gated = (sdpa_flat * ops::sigmoid(&gate_flat).unwrap()).unwrap();
    let gated_ref = take(&trace, "gated");
    println!("[9] gated        rel_L2 = {:.3e}", rel_l2(&gated, &gated_ref));

    let y_final = o_proj.forward(&gated.unsqueeze(0).unwrap()).unwrap().squeeze(0).unwrap();
    let y_ref = take(&trace, "y_final");
    println!("[10] y_final     rel_L2 = {:.3e}", rel_l2(&y_final, &y_ref));

    // Step 11: now run the actual SelfAttention::forward and verify it matches the same y_ref.
    // If this diverges from the inline reconstruction above, the bug is inside the library
    // wrapper (ordering, contiguity, etc.), not in the intermediate maths.
    use lumen_model::qwen3_5_moe::self_attn::{
        SelfAttention, SelfAttnDims, SelfAttnRuntime,
    };
    let dims = SelfAttnDims {
        hidden_size: 2048,
        num_heads: h,
        num_kv_heads: kv,
        head_dim: hd,
        attn_output_gate: true,
        rotary_dim,
    };
    let runtime = SelfAttnRuntime {
        dims,
        rope_theta,
        rms_norm_eps: eps,
    };
    let qkv_proj = Linear::new(
        Tensor::cat(
            &[
                Linear::new(take(&weights, "q_proj.weight"), None).weight(),
                Linear::new(take(&weights, "k_proj.weight"), None).weight(),
                Linear::new(take(&weights, "v_proj.weight"), None).weight(),
            ],
            0,
        )
        .unwrap(),
        None,
    );
    let mut attn = SelfAttention::new(
        runtime,
        qkv_proj.into(),
        Linear::new(take(&weights, "o_proj.weight"), None).into(),
        RmsNorm::new(take(&weights, "q_norm.weight"), eps),
        RmsNorm::new(take(&weights, "k_norm.weight"), eps),
    );
    // The MLX trace above was computed with a causal mask; match it here.
    let lib_mask = SelfAttention::prefill_causal_mask(seq_len, x.dtype(), &device).unwrap();
    let y_lib = attn
        .forward(&x, 0, Some(&lib_mask))
        .unwrap()
        .squeeze(0)
        .unwrap();
    println!("[11] lib forward rel_L2 = {:.3e}", rel_l2(&y_lib, &y_ref));
}
